#!/usr/bin/env python3
"""Post-scaffold validation for a project generated by project-init.

Usage:
    python3 validate.py [--root DIR] [--max-claude-lines N] [--no-tree]

Checks (all read-only):
    1. Prints the file tree (skips node_modules/.git/venvs) so it can be compared with the agreed layout.
    2. Frontmatter of .claude/skills/*/SKILL.md, .claude/agents/*.md and .claude/rules/**/*.md
       (plus a top-level SKILL.md if the root itself is a skill):
         - opens with '---' and parses as YAML (PyYAML if installed, a minimal key: value parser otherwise)
         - SKILL.md: 'name' (if present) equals the directory name; 'description' is non-empty
         - agents: 'name' equals the file stem; 'description' is non-empty
         - rules: 'paths' (if present) is a list or string
    3. .mcp.json, .claude/settings.json, .claude/settings.local.json, .claude-plugin/plugin.json parse as JSON.
    4. CLAUDE.md line count is <= --max-claude-lines (default 200).

Exit codes: 0 all checks passed, 1 at least one problem.
"""
import argparse
import json
import re
import sys
from pathlib import Path

IGNORE = {"node_modules", ".git", ".venv", "venv", "__pycache__", "dist", "build", ".next"}

try:  # PyYAML is optional
    import yaml  # type: ignore

    def parse_yaml(text: str):
        data = yaml.safe_load(text)
        return data if isinstance(data, dict) else {}
except ImportError:  # pragma: no cover - exercised only where PyYAML is missing
    yaml = None

    def parse_yaml(text: str):
        """Minimal fallback: top-level `key: value` lines only. Enough to check name/description."""
        data = {}
        for line in text.splitlines():
            m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
            if m:
                v = m.group(2).strip()
                if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
                    v = v[1:-1]
                data[m.group(1)] = v
        return data


def split_frontmatter(text: str):
    """Return (frontmatter_text, ok). ok is False when the file does not start with a '---' block."""
    if not text.startswith("---"):
        return "", False
    parts = text.split("---", 2)
    if len(parts) < 3:
        return "", False
    return parts[1], True


def tree(root: Path, prefix: str = ""):
    entries = sorted(
        [e for e in root.iterdir() if e.name not in IGNORE],
        key=lambda e: (not e.is_dir(), e.name.lower()),
    )
    lines = []
    for i, e in enumerate(entries):
        last = i == len(entries) - 1
        lines.append(f"{prefix}{'└── ' if last else '├── '}{e.name}{'/' if e.is_dir() else ''}")
        if e.is_dir():
            lines.extend(tree(e, prefix + ("    " if last else "│   ")))
    return lines


def check_frontmatter(path: Path, expected_name, problems, require_description=True):
    text = path.read_text(encoding="utf-8")
    fm_text, ok = split_frontmatter(text)
    if not ok:
        problems.append(f"{path}: missing '---' frontmatter block")
        return None
    try:
        fm = parse_yaml(fm_text)
    except Exception as e:  # yaml.YAMLError or anything else
        problems.append(f"{path}: frontmatter is not valid YAML ({e})")
        return None
    if expected_name is not None and "name" in fm and str(fm["name"]) != expected_name:
        problems.append(f"{path}: name '{fm['name']}' != '{expected_name}'")
    if require_description and not str(fm.get("description", "")).strip():
        problems.append(f"{path}: description is empty or missing")
    return fm


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".")
    ap.add_argument("--max-claude-lines", type=int, default=200)
    ap.add_argument("--no-tree", action="store_true")
    args = ap.parse_args()
    root = Path(args.root)
    if not root.is_dir():
        print(f"validate: {root} is not a directory", file=sys.stderr)
        return 1

    problems, checked = [], []

    if not args.no_tree:
        print(f"{root.resolve().name}/")
        print("\n".join(tree(root)))
        print()

    # 2. frontmatter
    skill_files = sorted(root.glob(".claude/skills/*/SKILL.md"))
    if (root / "SKILL.md").exists():
        skill_files.append(root / "SKILL.md")
    for f in skill_files:
        check_frontmatter(f, f.parent.resolve().name, problems)
        checked.append(f)
    for f in sorted(root.glob(".claude/agents/*.md")):
        fm = check_frontmatter(f, f.stem, problems)
        if fm is not None and "name" not in fm:
            problems.append(f"{f}: agents require a 'name' field")
        checked.append(f)
    for f in sorted(root.glob(".claude/rules/**/*.md")):
        text = f.read_text(encoding="utf-8")
        if text.startswith("---"):
            fm = check_frontmatter(f, None, problems, require_description=False)
            if fm is not None and "paths" in fm and not isinstance(fm["paths"], (list, str)):
                problems.append(f"{f}: 'paths' must be a list or string")
        checked.append(f)

    # 3. JSON
    for rel in (".mcp.json", ".claude/settings.json", ".claude/settings.local.json", ".claude-plugin/plugin.json"):
        f = root / rel
        if f.exists():
            try:
                json.loads(f.read_text(encoding="utf-8"))
            except json.JSONDecodeError as e:
                problems.append(f"{f}: invalid JSON ({e})")
            checked.append(f)

    # 4. CLAUDE.md length
    for rel in ("CLAUDE.md", ".claude/CLAUDE.md"):
        f = root / rel
        if f.exists():
            n = sum(1 for _ in f.open(encoding="utf-8"))
            print(f"{rel}: {n} lines (limit {args.max_claude_lines})")
            if n > args.max_claude_lines:
                problems.append(f"{f}: {n} lines > {args.max_claude_lines}; split into .claude/rules/")
            checked.append(f)

    if yaml is None:
        print("note: PyYAML not installed; frontmatter checked with a minimal parser")
    print(f"checked {len(checked)} file(s)")
    if problems:
        print("\nPROBLEMS:")
        for p in problems:
            print(f"  - {p}")
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
